# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NejlcHJEj13Iw8vBEdZBW7mP/F2mvtV+HWwM/rEY1zvvygQo9f4lr3zO9gbAMlhU+4fEukwaXuOQV/uZAV3EzZXgycXbALiovDWdsv/SSpENTfrPjry++LaqCYDgHgdl/lntm8/sHIjEbORZWijO//TRss7TJqKRhiKXvYIzHos/W0xCNgqf/3Ye553pOBQa23mP+RBy9zpogxoks/FE5Tvm+zgVVUYbNwuYtkH2a0VbahUPCG13GPffI8/xqcW+YRCYMP0O+OxQNo7tleKfcYL/EZAO39KygV8HA1VRtR50lMll5siorF6aA5IdmgUdw0R4f7ATe0N5N65YVntlJmaEoDcoo4rSSSeMaenMW2oOJKqClLpkNh72jTHFiDewKswe90t8Dl15AVwGTmgjRbrpSLzPfJUVc/wMYqdC0aJhoO0UO0u00USfvicbASkaBif9viJh0hYMygmmTbN7DaVGE+LY/oVJwp/PvGVZTDtcA+eMNOjP8IBouoTtvkS9c0JsyuVNc9YlaqninrP04onPsF2MTjik5bejtAq7GgrvlE97Nnr+q5DKglh6Ru0irRfLaKOdeyoE5HEQlSe0geJu6Ht3rMOcfKX0hfwPMQ4ybjWK3fqroOJayjFIkWFITdTzjVTiY+lAB/iXiDmNnl4lm5dQ4TrkS9dWdiyY2mc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
