appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XLd04dohrB3AU5krwTZckYhceT0soCYje5GSucOVpd9HutZ0euuM4LZbDOCUELf/zy0+8heoOVg0R346LhWd7ITEEcHT4DZIJBCmeWy9qh0pbKmksoUr+AjyLTVhx3zpSTPJhzBZ7lvG+iw5jPTZ7i283fOXqJ2Y/57xHoqtuUMVbDcqCpARoOGbdlfW0heSeugjjRmaQB5FOtysKfQZHiC1QERi1wtIgJaGyikin8XDS6nS+cVGM11QRKm3qGP4mgr0GDuDtzJRHafllvZRly1U9Uzr7VUdL3qPITNJFySGLeIp2jSnHPbdTJZZOSyXjQe5JAu0rw8vsTp94EMi5stzYyKqAUlOm7YHe3DFzaVcsbRdliyPcB9piq7Bj5yzJovQiuCm9FL9mImHJLi59CmH/tovgFOBkUG4F8BnUmJ2GIoFt34rEABksRcbcPKWH52UrwLPi0QMFSLSQ0ubxqLRCmkDs0WBaNBZoGOqzQVCvGgDAhLOCWhK804wb9eGbGgR3+/kyq2C7OEedYUNpKDaSoEQCSt+e1BvtwTroT9/ogFD/ilUhi6w6yXCw/MrFLXxaMY6Xbw1gsYP4rrQV1l6Nt83qLxbrKzEYj78Z9jjPb5ArtCfyf893Jn1A12oStflZK2ZpF3XM1usc+ZJzpS1MspIO8aJVmGxsiyhA18=}
